version: "3.9"

services:
  www:
      build: .
      restart: always
      ports:
            - '8000:80'
      volumes:
            - ./www:/var/www/html      
  db:
      image: mysql
      restart: always
      ports:
            - '3306:3306'
      environment:
            MYSQL_DATABASE: meudb
            MYSQL_USER: claudinei
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 12345
      volumes:
            - db_data:/var/lib/mysql              
volumes:
